Single source of truth for version information.
LLNL/msr-safe pull request #168
Opened 2024-09-13 06:34 UTC by rountree

Fixes #167 

msr_version.h
	#defines for major, minor, and patch versions of msr-safe
	as well as helper macros to generate _u32 and string
	representation.

Makefile
	Removes CURRENT_VERSION and -DVERSION from build.
	msrsave now gets the version string from msr_version.h

msrsave_main.c
msr_entry.c
	Now #includes msr_version.h and uses MSR_SAFE_VERSION_STR

msr_safe.h
	Repurposes a bit of struct padding to hold a _u32-format
	msr-safe version number.

README.md
	Updates documentation of struct msr_batch_array to note
	the new version field.  Explains how this will remain
	unused in the 1.x.y series.  Version 2.x.y will begin
	checking this version field to make sure what the user
	compiled against is the same version as the loaded
	kernel module.  This is necessary due to anticipated
	batch API changes in version 2.0.0.

Tested on serif (Ubuntu 24.04.1 LTS, Linux 6.8.0, gcc 13.2.0)

2024-09-17 23:05 UTC, slabasan commented on msr_entry.c
> +MODULE_VERSION( MSR_SAFE_VERSION_STR );
Remove extra spaces

2024-09-17 23:05 UTC, slabasan requested changes
One change

2024-09-19 19:02 UTC, rountree commented on msr_entry.c
> +MODULE_VERSION( MSR_SAFE_VERSION_STR );
Fixed.

2024-09-23 16:14 UTC, slabasan approved these changes

2024-09-23 16:15 UTC, merged